/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as IndexRouteImport } from './routes/index'

const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/reserve': typeof ReserveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/reserve': typeof ReserveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/reserve': typeof ReserveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/approach' | '/contact' | '/reserve'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/approach' | '/contact' | '/reserve'
  id: '__root__' | '/' | '/approach' | '/contact' | '/reserve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproachRoute: typeof ApproachRoute
  ContactRoute: typeof ContactRoute
  ReserveRoute: typeof ReserveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproachRoute: ApproachRoute,
  ContactRoute: ContactRoute,
  ReserveRoute: ReserveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
